schedules:
  - cron: "30 2 * * *"
    displayName: Run nightly build
    branches:
      include:
        - master
    always: true

jobs:
  - job: Test
    strategy:
      matrix:
        imbalanced-learn:
          TARGET: imbalanced-learn
    pool:
      vmImage: ubuntu-20.04
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.10"
      - bash: |
          pip install packaging
          pip install git+https://github.com/numba/texasbbq.git
        displayName: Install dependencies
      - bash: python switchboard.py -t $TARGET
        displayName: Run tests
