schedules:
  - cron: "30 2 * * *"
    displayName: Run nightly build
    branches:
      include:
        - master
    always: true

jobs:
  - job: Test
    strategy:
      matrix:
        imbalanced-learn:
          TARGET: imbalanced-learn
        shap:
          TARGET: shap
    pool:
      vmImage: ubuntu-18.04
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.8"
      - bash: pip install git+https://github.com/numba/texasbbq.git
        displayName: Install dependencies
      - bash: python switchboard.py -t $TARGET
        displayName: Run tests
