schedules:
  - cron: "30 2 * * *"
    displayName: Run nightly build
    branches:
      include:
        - master
    always: true

jobs:
  - job: Test
    strategy:
      matrix:
        imbalanced-learn:
          TARGET: imbalanced-learn
    pool:
      vmImage: ubuntu-18.04
    steps:
      - bash: echo "$TARGET"
        displayName: Testing
